name T2exp
comment This experiment tests different algorithms when running the CPU-Intensive and Mixed-Load workload in parallel
run T2run algorithm FCFS key "FCFS"
run T2run algorithm SJF key "SJF"
run T2run algorithm RR 1 key "RR 1"
run T2run algorithm SJFA 0.5 key "SJFA 0.5"
run T2run algorithm FCFS key "FCFS"
run T2run algorithm SJF key "SJF"
run T2run algorithm RR 1 key "RR 1"
run T2run algorithm SJFA 0.5 key "SJFA 0.5"
